apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmyshow-app
  template:
    metadata:
      labels:
        app: bookmyshow-app
    spec:
      containers:
      - name: bookmyshow-app
        image: REPLACE_WITH_ECR_URI:REPLACE_WITH_IMAGE_TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
